package com.ant.mcskyblock.common.world.level.levelgen;

import com.ant.mcskyblock.common.world.level.levelgen.islandtype.*;
import net.minecraft.world.level.block.Blocks;

import java.util.Map;

import static java.util.Map.entry;

public class BiomeIslands {
    public static final Map<String, IslandType> SETTINGS = Map.<String, IslandType>ofEntries(
            entry("the_void", new VoidIslandType()),
            entry("plains", new FluidAccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.WATER, Blocks.POTTED_OAK_SAPLING)),
            entry("sunflower_plains", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.SUNFLOWER)),
            entry("snowy_plains", new AccessoryIslandType(Blocks.SNOW_BLOCK, Blocks.SNOW)),
            entry("ice_spikes", new AccessoryIslandType(Blocks.BLUE_ICE, Blocks.PACKED_ICE)),
            entry("desert", new AccessoryIslandType(Blocks.SANDSTONE, Blocks.CACTUS)),
            entry("swamp", new AccessoryIslandType(Blocks.MUD, Blocks.POTTED_CORNFLOWER)),
            entry("mangrove_swamp", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_MANGROVE_PROPAGULE)),
            entry("forest", new AccessoryIslandType(Blocks.PODZOL, Blocks.POTTED_SPRUCE_SAPLING)),
            entry("flower_forest", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.LILAC)),
            entry("birch_forest", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.BIRCH_SAPLING)),
            entry("dark_forest", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_DARK_OAK_SAPLING)),
            entry("old_growth_birch_forest", new VoidIslandType()),
            entry("old_growth_pine_taiga", new VoidIslandType()),
            entry("old_growth_spruce_taiga", new VoidIslandType()),
            entry("taiga", new VoidIslandType()),
            entry("snowy_taiga", new VoidIslandType()),
            entry("savanna", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_ACACIA_SAPLING)),
            entry("savanna_plateau", new VoidIslandType()),
            entry("windswept_hills", new VoidIslandType()),
            entry("windswept_gravelly_hills", new VoidIslandType()),
            entry("windswept_forest", new VoidIslandType()),
            entry("windswept_savanna", new VoidIslandType()),
            entry("jungle", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_JUNGLE_SAPLING)),
            entry("sparse_jungle", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_JUNGLE_SAPLING)),
            entry("bamboo_jungle", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.BAMBOO_SAPLING)),
            entry("badlands", new AccessoryIslandType(Blocks.TERRACOTTA, Blocks.POTTED_DEAD_BUSH)),
            entry("eroded_badlands", new AccessoryIslandType(Blocks.RED_TERRACOTTA, Blocks.POTTED_DEAD_BUSH)),
            entry("wooded_badlands", new AccessoryIslandType(Blocks.ORANGE_TERRACOTTA, Blocks.POTTED_OAK_SAPLING)),
            entry("meadow", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_OAK_SAPLING)),
            entry("grove", new AccessoryIslandType(Blocks.GRASS_BLOCK, Blocks.POTTED_OAK_SAPLING)),
            entry("snowy_slopes", new AccessoryIslandType(Blocks.SNOW_BLOCK, Blocks.POTTED_WITHER_ROSE)),
            entry("frozen_peaks", new AccessoryIslandType(Blocks.PACKED_ICE, Blocks.POWDER_SNOW)),
            entry("jagged_peaks", new VoidIslandType()),
            entry("stony_peaks", new VoidIslandType()),
            entry("river", new SimpleIslandType(Blocks.WATER)),
            entry("frozen_river", new SimpleIslandType(Blocks.ICE)),
            entry("beach", new SimpleIslandType(Blocks.SAND)),
            entry("snowy_beach", new VoidIslandType()),
            entry("stony_shore", new VoidIslandType()),
            entry("warm_ocean", new VoidIslandType()),
            entry("lukewarm_ocean", new VoidIslandType()),
            entry("deep_lukewarm_ocean", new VoidIslandType()),
            entry("ocean", new VoidIslandType()),
            entry("deep_ocean", new VoidIslandType()),
            entry("cold_ocean", new VoidIslandType()),
            entry("deep_cold_ocean", new VoidIslandType()),
            entry("frozen_ocean", new VoidIslandType()),
            entry("deep_frozen_ocean", new VoidIslandType()),
            entry("mushroom_fields", new AccessoryIslandType(Blocks.MYCELIUM, Blocks.POTTED_RED_MUSHROOM)),
            entry("dripstone_caves", new AccessoryIslandType(Blocks.DRIPSTONE_BLOCK, Blocks.POINTED_DRIPSTONE)),
            entry("lush_caves", new AccessoryIslandType(Blocks.MOSS_BLOCK, Blocks.POTTED_FLOWERING_AZALEA)),
            entry("deep_dark", new AccessoryIslandType(Blocks.SCULK, Blocks.SCULK_VEIN)),
            entry("nether_wastes", new AccessoryIslandType(Blocks.NETHERRACK, Blocks.POTTED_BROWN_MUSHROOM)),
            entry("warped_forest", new AccessoryIslandType(Blocks.WARPED_NYLIUM, Blocks.POTTED_WARPED_FUNGUS)),
            entry("crimson_forest", new AccessoryIslandType(Blocks.CRIMSON_NYLIUM, Blocks.POTTED_CRIMSON_FUNGUS)),
            entry("soul_sand_valley", new AccessoryIslandType(Blocks.SOUL_SOIL, Blocks.BONE_BLOCK)),
            entry("basalt_deltas", new AccessoryIslandType(Blocks.BASALT, Blocks.MAGMA_BLOCK)),
            entry("the_end", new VoidIslandType()),
            entry("end_highlands", new VoidIslandType()),
            entry("end_midlands", new VoidIslandType()),
            entry("small_end_islands", new VoidIslandType()),
            entry("end_barrens", new AccessoryIslandType(Blocks.END_STONE, Blocks.CHORUS_FLOWER))
    );
}
