modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
modId="mcskyblock"
version="${file.jarVersion}"
displayName="MC SkyBlock"
logoFile="mcskyblock.png"
credits="Vaskii (Botania GoG) - https://github.com/Vazkii/Botania"
authors="Ant"
description='''
This mod adds a new world generation type for a barebones skyblock experience
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
